import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Typography } from '@mui/material';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Image from 'next/image';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Kjeldsen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Box
          sx={{
            background: '#F9F9F9',
            backgroundRepeat: 'no-repeat',
            backgroundImage: 'url("/img/pitch_vector.svg")',
            backgroundSize: 'contain',
            backgroundPosition: 'right center',
          }}
          display={'flex'}
          justifyContent={'center'}
          paddingY={4}>
          <Box
            display={'flex'}
            justifyItems={'start'}
            width={'100%'}
            alignItems={'center'}
            paddingX={4}>
            <Box>
              <Image
                width={153}
                height={164}
                src="/img/vector.svg"
                alt="Kjeldsen svg"
              />
            </Box>
            <Box sx={{ maxWidth: 860, paddingLeft: '42px' }}>
              <Typography
                sx={{ fontWeight: 700, fontSize: '32px', color: '#FF3F84' }}>
                ALPHA v1.0
              </Typography>
              <Typography sx={{ fontWeight: 400, fontSize: '22px' }}>
                Welcome to v1.0 of the Kjeldsen Closed Alpha.
              </Typography>
              <Typography>
                A small team of developers is waiting to hear your feedback, try
                to be kind but report anything you see that could be a bug or an
                improvement that you would like to see in this game in the
                future.
              </Typography>
            </Box>
          </Box>
        </Box>

        {/* <Box
          width={1220}
          height={200}>
          <Image
            width={1220}
            height={200}
            src="/img/intro.png"
            alt="Kjeldsen Intro"
            style={{
              width: '100%',   // Make it scale to parent container
              height: 'auto',  // Maintain aspect ratio
            }}
          />
        </Box> */}

        {/* <Typography variant="h1" component="h1">
          Welcome to Kjeldsen
        </Typography> */}
      </>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
