openapi: 3.0.0
info:
  version: 1.0.0
  title: Auth API

tags:
  - name: auth

paths:

  /auth/unauthorized:
    get:
      summary: Unauthorized access endpoint
      operationId: unauthorized
      tags:
        - auth
      description: This endpoint is mapped to the `shiro.unauthorizedUrl` property in application.properties
      responses:
        '401':
          description: Unauthorized

  /auth/login:
    post:
      summary: Login
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/LoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /auth/me:
    get:
      summary: Get currently logged-in user
      operationId: me
      tags:
        - auth
      responses:
        "200":
          description: Logged-in user found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /auth/logout:
    post:
      summary: Logout
      operationId: logout
      tags:
        - auth
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /auth/register:
    post:
      summary: Register
      operationId: register
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/RegisterRequest"
      responses:
        "201":
          description: Registration successful
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

components:

  requestBodies:

    LoginRequest:
      description: User request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginRequest"

    RegisterRequest:
      description: User request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RegisterRequest"

  responses:

    DefaultErrorResponse:
      description: Unexpected error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"

  schemas:

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    RegisterRequest:
      type: object
      required:
        - email
        - password
        - teamName
      properties:
        email:
          type: string
        password:
          type: string
        teamName:
          type: string

    Error:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    UserDetailsResponse:
      type: object
      required:
        - id
        - email
        - teamId
      properties:
        id:
          type: string
        email:
          type: string
        teamId:
          type: string
