import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Typography } from '@mui/material'
import Link from 'next/link'

const Gandul: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kjeldsen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Box
          css={{
            padding: '5rem',
          }}>
          <Typography variant="h3" component="h1">
            &quot;Ponte a trabajar gandul, y pagame las cuotas que me debes&quot;
          </Typography>
          <Typography variant="h1" component="h1" sx={{ marginBottom: '1rem' }}>
            - Aristolete
          </Typography>
          <iframe
            width="560"
            height="315"
            src="https://www.youtube.com/embed/b2RbHERb7ZM?start=9"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen></iframe>
        </Box>
      </>
    </>
  )
}

export default Gandul
