import type { NextPage } from 'next'
import Head from 'next/head'
import { Box } from '@mui/material'
import Grid from '@/shared/components/Grid/Grid'
import { SampleTeam } from '@/data/SampleTeam'
import TeamDetails from '@/shared/components/TeamDetails'
import PlayerTactics from '@/shared/components/PlayerTactics'
import TeamTactics from '@/shared/components/TeamTactics'
import { players } from '@/data/SamplePlayer'
import { samplePlayerColumn } from '@/data/samplePlayerColumn'
import useSWR from 'swr'

const Team: NextPage = () => {
  const fetcher = (url: string) => fetch(url).then((res) => res.json())

  // const { data, error, isLoading } = useSWR('https://official-joke-api.appspot.com/random_joke', fetcher)
  const { data, error, isLoading } = useSWR('http://localhost:8082/player', fetcher)

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>

  data.forEach((element: any) => console.log(element))

  return (
    <>
      <Head>
        <title>Kjeldsen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box>
        <Box sx={{ display: 'flex', marginBottom: '2rem', alignItems: 'center' }}>
          <TeamDetails {...SampleTeam} />
          <PlayerTactics />
          <TeamTactics />
        </Box>
        <Box sx={{ minWidth: '1200px' }}>
          <Grid rows={players} columns={samplePlayerColumn} />
        </Box>
        <Box sx={{ minWidth: '1200px' }}>
          <Grid rows={data} columns={samplePlayerColumn} />
        </Box>
      </Box>
    </>
  )
}

export default Team
