import type { NextPage } from 'next';
import Head from 'next/head';
import { Typography } from '@mui/material';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useSession } from 'next-auth/react';
import DoubleDropdown from '@/shared/components/Player/DoubleDropdown';
import { NestedMenu } from '@/shared/components/Player/NestedMenu';

const Home: NextPage = () => {
  const { data: userData, status: sessionStatus } = useSession({
    required: true,
  });
  return (
    <>
      <Head>
        <title>Kjeldsen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Typography variant="h1" component="h1">
          Dashboarda
        </Typography>
        <NestedMenu />
      </>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
