export enum PlayerPosition {
  CENTRE_BACK = 'centreBack',
  AERIAL_CENTRE_BACK = 'aerialCentreBack',
  SWEEPER = 'sweeper',
  LEFT_BACK = 'leftBack',
  RIGHT_BACK = 'rightBack',
  LEFT_WINGBACK = 'left_wingback',
  RIGHT_WINGBACK = 'rightWingback',
  DEFENSIVE_MIDFIELDER = 'defensiveMidfielder',
  CENTRE_MIDFIELDER = 'centreMidfielder',
  LEFT_MIDFIELDER = 'leftMidfielder',
  RIGHT_MIDFIELDER = 'rightMidfielder',
  LEFT_WINGER = 'leftWinger',
  OFFENSIVE_MIDFIELDER = 'offensiveMidfielder',
  RIGHT_WINGER = 'rightWinger',
  FORWARD = 'forward',
  AERIAL_FORWARD = 'aerialForward',
  STRIKER = 'striker',
  AERIAL_STRIKER = 'aerialStriker',
  GOALKEEPER = 'goalkeeper',
}
