import type { NextPage } from 'next'
import Head from 'next/head'
import Collapsible from '@/shared/components/Collapsible'
import Box from '@mui/material/Box'
import Grid from '@/shared/components/Grid/Grid'
import { players } from '@/data/SamplePlayerTraining'
import { sampleTrainingColumn } from '@/data/sampleTrainingColumn'
import { PlayerProvider } from 'contexts/PlayerContext'

const Training: NextPage = () => {
  return (
    <>
      <PlayerProvider>
        <Head>
          <title>Kjeldsen</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <>
          <Box>
            <Collapsible open title="Yesterday's Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
            <Collapsible title="Yesterday -1 Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
            <Collapsible title="Yesterday -2 Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
            <Collapsible title="Yesterday -3 Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
            <Collapsible title="Yesterday -4 Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
            <Collapsible title="Yesterday -5 Training Report">
              <Box>
                <Grid rows={players} columns={sampleTrainingColumn} />
              </Box>
            </Collapsible>
          </Box>
        </>
      </PlayerProvider>
    </>
  )
}

export default Training
