import type { NextPage } from 'next'
import Head from 'next/head'
import { Typography } from '@mui/material'

const Training: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kjeldsen</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <Typography variant="h1" component="h1">
          This is the training page
        </Typography>
      </>
    </>
  )
}

export default Training
