export enum PlayerOrder {
  PASS_FORWARD = 'PASS_FORWARD',
  LONG_SHOT = 'LONG_SHOT',
  CHANGE_FLANK = 'CHANGE_FLANK',
  PASS_TO_AREA = 'PASS_TO_AREA',
  DRIBBLE_TO_AREA = 'DRIBBLE_TO_AREA',
  WALL_PASS = 'WALL_PASS',
  NONE = 'NONE',
}
