server:
  port: 8083

spring:
  application:
    name: match-service
  profiles:
    active: 'local'

  datasource:
    url: jdbc:h2:mem:game-db
    # For saving db to file:
    # url: jdbc:h2:file:./game-db
    username: admin
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # Turn these on to debug database issues
        # format_sql: true
        # show_sql: true
        # use_sql_comments: true
    defer-datasource-initialization: true
    generate-ddl: true
