server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service
  main:
    allow-circular-references: true

hosts:
  main-service: 'http://localhost:8081'

zuul:
  sensitive-headers:
  routes:
    main-service:
      path: /main-service/**
      url: ${hosts.main-service}

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${hosts.main-service}/oauth/token_key
