package com.kjeldsen.match.entities.duel;

public enum DuelOrigin {

    /*
     * The origin of the play records whether the play was generated by a modifier such as a player
     * order or some other instruction, or whether it was the engine default.
     */

    DEFAULT,
    PLAYER_ORDER,
}
