name: "Maven Build"
description: "Builds a mvn service"

inputs:
  PATH:
    required: true
    description: "The path of the item to built"
  NAME:
    required: true
    description: "The name of the item to built"
  AWS_ECR_URI:
    required: true
    description: "AWS ECR service URI"
  AWS_CICD_ACCESS_KEY:
    required: true
    description: "AWS ECR service access key"
  AWS_CICD_SECRET_ACCESS_KEY:
    required: true
    description: "AWS ECR service secret access key"
  SLACK_CICD_WEBHOOK:
    description: "Slack CI/CD channel webhook"
  SLACK_NOTIFICATION:
    description: "Activates Slack Notification"
    default: "true"
  DOCKER_IMAGE_GENERATION:
    description: "Indicates if the Docker image should be generated and published to AWS ECR"
    default: "true"
  MVN_DEPLOY:
    description: "Indicates if the Maven artifact should be publish to AWS Code Artifact"
    default: "false"

runs:
  using: "composite"

  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "17"
        cache: "maven"

    - name: AWS Configure
      id: ecr_configure
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_CICD_ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.AWS_CICD_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Set CODEARTIFACT_AUTH_TOKEN
      id: set_codeartifact_auth_token
      run: |
        echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain kjeldsen --domain-owner 324037306405 --region eu-west-1 --query authorizationToken --output text)" >> $GITHUB_ENV
      shell: bash

    - name: Build
      id: build
      run: |
        cd ${{ inputs.PATH }}/${{ inputs.NAME }}
        mvn clean install -U
      shell: bash

    - name: Deploy
      id: deploy
      if: |
        steps.ecr_configure.outcome == 'success' && 
        inputs.MVN_DEPLOY  == 'true'
      run: |
        cd ${{ inputs.PATH }}/${{ inputs.NAME }}
        mvn deploy -Dmaven.deploy.version=${{ env.VERSION }}
      shell: bash

    - name: Generate ECR Variables
      id: ecr_variables
      if: |
        steps.ecr_configure.outcome == 'success' && 
        inputs.DOCKER_IMAGE_GENERATION  == 'true'
      run: |
        echo "ECR_IMAGE_NAME=${{ inputs.AWS_ECR_URI }}/${{ inputs.NAME }}:${{ env.VERSION }}" >> $GITHUB_ENV
      shell: bash

    - name: Login to Amazon ECR
      id: login_ecr
      if: steps.ecr_variables.outcome == 'success'
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      id: ecr_push
      if: steps.login_ecr.outcome == 'success'
      run: |
        cd ${{ inputs.PATH }}/${{ inputs.NAME }}
        docker build -t ${{ env.ECR_IMAGE_NAME }} .
        docker push ${{ env.ECR_IMAGE_NAME }}
      shell: bash

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: inputs.SLACK_NOTIFICATION  == 'true'
      env:
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github-actions.s3.eu-west-1.amazonaws.com/Octocat.png
        SLACK_WEBHOOK: ${{ inputs.SLACK_CICD_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_TITLE: Built ${{ inputs.NAME }}
        SLACK_FOOTER: "CI successfully finished"
        MSG_MINIMAL: actions url, commit
