server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: player-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: root
      database: admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: ${spring.application.name}

springdoc:
  version: "@springdoc.version@"
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
  show-actuator: true

kafka:
  topics:
    auth-signup: AuthSignup

hosts:
  auth-service:
    url: 'http://localhost:8081'

security:
  oauth2:
    client-id: client_id
    client-secret: client_secret
