server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: com.novemberain.quartz.mongodb.MongoDBJobStore
            mongoUri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}
            collectionPrefix: quartz_
            dbName: quartz_db

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}
