server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  quartz:
    properties:
      org:
        quartz:
            quartzDataSource:
              URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
              user: ${POSTGRES_USER}
              password: ${POSTGRES_PASSWORD}

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}
