server:
  port: ${SERVER_PORT:15001}
  error:
    include-message: always
  forward-headers-strategy: framework

spring:
  application:
    name: main-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:admin}${MONGO_OPTIONS:?retryWrites=false}
  management:
    server:
      port: ${ACTUATOR_SERVER_PORT:15002}
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: com.novemberain.quartz.mongodb.MongoDBJobStore
            mongoUri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:admin}${MONGO_OPTIONS:?retryWrites=false}
            collectionPrefix: quartz_
            dbName: quartz_db

logging:
  level:
    com.kjeldsen: INFO
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    operations-sorter: alpha
#    tags-sorter: alpha
  show-actuator: true

internal:
  api:
    key: my-secret-key

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS:86400} # 1 day
    public-endpoints:
      - /
      - /swagger-ui/**
      - /api-docs/**
      - /swagger-ui.html
      - /auth/register
      - /auth/token
    public-key: -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzErYqgLxRBbRE5YnVV0m
      Q5k8+Oj/uMbKfkyi6AE1MIRVtDlM8xM4KxRWsqOTbLhalB7XwaNGj7jxdZvKhvbb
      e63ATpOUZoLh2lgXIQ0zU98wsNv33nVWLR+Vh7GOAC36e0JG6UnZLUwHPfdjawrX
      76owaMYmzPDi7GzpJs6PW27OCJbJDClZP2lJS2lRdFwS6T3C30JtK0Da53dLRsay
      rqjkbOjfFZkV1PrxdcVvf7fFRhn8hBg65hQj3+X/uo7TKJStdvS3ERne1a9rzGJH
      5nWnX2rQe+6sYFGfrqugX2ZmaWPB82TqQ4jGUugjXyt7y6aSAb5RzOz2Mc7a375B
      SwIDAQAB
      -----END PUBLIC KEY-----
    private-key: -----BEGIN PRIVATE KEY-----
      MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDMStiqAvFEFtET
      lidVXSZDmTz46P+4xsp+TKLoATUwhFW0OUzzEzgrFFayo5NsuFqUHtfBo0aPuPF1
      m8qG9tt7rcBOk5RmguHaWBchDTNT3zCw2/fedVYtH5WHsY4ALfp7QkbpSdktTAc9
      92NrCtfvqjBoxibM8OLsbOkmzo9bbs4IlskMKVk/aUlLaVF0XBLpPcLfQm0rQNrn
      d0tGxrKuqORs6N8VmRXU+vF1xW9/t8VGGfyEGDrmFCPf5f+6jtMolK129LcRGd7V
      r2vMYkfmdadfatB77qxgUZ+uq6BfZmZpY8HzZOpDiMZS6CNfK3vLppIBvlHM7PYx
      ztrfvkFLAgMBAAECggEAJl6kZQIaeHRknm4kQxc0uZuNZR618Ol9XM1eB386kzs3
      sZrVhg4FDapLQlAQv2m8sXc9hMP628GbsEArgL/ap1cR+HAlfj901gKXjYCiNE2G
      IqGd421cWytEdXD2v7fjBMWE9goFvUk7Tvso9BDcT8pCP1uALBvOMyOdgslnCX/m
      3HRibwMkvbnB0ahQZ6StgAyr8eZp6NyQU3Bo5jcnuFeVO71YR4xecI1rn6vR7sa0
      lcioBnSm4HACd9EfsCOFb11FgQ6ihoJeLZrRTk0gpIXR2YHMKddbbuK84aqjBEo1
      q2grYoHNBYMj1AKmtrn0CFL9qrUU9o8GZrgz61t90QKBgQD9d1C7mlKa8GD3Oy9s
      R5wHEIy6ERrQETqPglxC84Tg4BWca56rN00UzDas9xFvwO+LCVCvz0Vc538K/8sQ
      jaDQDzhNXJEfFmAdQqfKbe0cpvy8Qp0jP4NUOi+MpjGE3q53B2bb++wOX34k9Q3U
      +G6Kn3cvrQVCj2WTCVGfAI+mMwKBgQDOVa7QNS40BuU5LjwOkDQYT1wzSIV/tWpz
      6LLewhuy1CSQCrhTllKzgHCoIp9ARLTmGadh5Z89eaqFVukiRSz0gFuL1YD9WEa6
      5hilEYnX1dSrptMslqEZ1W8ij4bs6tL5GnJjrN3Xju8A+I67mkgq4XVJIVuJ6cbC
      UDihJThwiQKBgQDUYKI7303x1xJYdbYBs2rQHJTd3zEpQBZiYudtjeA8EGbrPt2f
      NuIWWBpECW0Jx46vYCnEdhb3hl1T2QrMHu+tBeO2JqbOdpAoVE6FdmAkDuNb1zEV
      dMVU0MBAyIxbeb6Tq5cLImYjkO4Ah3iEh3kQHBfg0cfDgqWoczl50h2LMwKBgQC/
      A8V9TO5EDeohIHNKzCbeJoHlnAqyqsEtIsyMukgoKoraqoHwJ+bR9GLW1I53UePi
      bPdvAsODhuHc5ROYvU+b3kRh1LrATvvTxHYmQnFI1dU3P46Z5ayonNVwukyfgdjj
      8Z7aNct95f3O+Uwx0udigywwEmiK6VguxVNXo3x3eQKBgQCF6XTnqYV4LtCa/I3B
      icSOVO7RWz2Dqx2v9xRi7nid3E/8tA+lrUxF1pARgFlGz7LnQmb+PMk8swcBDpPb
      xNvF9ECNsZS/69xdFsa7+eZtm6vZHVUQ+tzOHyIip2HkQ8P4RIjm4HcLHzStkCX5
      nGhbm8wByaJD5hre7M7B2VKtfg==
      -----END PRIVATE KEY-----
