security:
  oauth2:
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}

logging:
  level:
    com.kjeldsen: INFO
    root: ERROR

server:
  ssl:
    trust-store: ${TRUST_STORE_PATH}
    trust-store-password: ${TRUST_STORE_PASSWORD}
