import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Button, Typography } from '@mui/material'
import Grid from '@/shared/components/Grid/Grid'
import { sampleRows, sampleColumns } from '@/shared/components/Grid/PlayerGrid'
import PlayerDetails from '@/shared/components/PlayerDetails'
import { PlayerStats, samplePlayer } from '@/data/SamplePlayer'
import { useRouter } from 'next/router'
import { PlayerContext, PlayerProvider } from 'contexts/PlayerContext'
import { useContext } from 'react'
import { connectorAPI } from '@/libs/fetcher'
import useSWR from 'swr'

const Player: NextPage = () => {
  const playerContext = useContext(PlayerContext)
  let player = {} as PlayerStats
  console.log('contextplayer', playerContext)
  const router = useRouter();
  const {id} = router.query;

  if (playerContext?.selectedPlayer === null) {
    console.log('id is', id)

    const { data, error, isLoading } = useSWR(`/player/${id}`, connectorAPI)
    if (error) return <div>failed to load</div>
    if (isLoading) return <div>loading...</div>
    player = data
    console.log('player is null', player)
  } else {
    console.log('player is not null')
    player = playerContext?.selectedPlayer as PlayerStats
  }

  return (
    <>
      <PlayerProvider>
        <Head>
          <title>Kjeldsen</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Box>
          <PlayerDetails player={player} />
          <Box sx={{ marginBottom: '1rem' }}>
            <Button variant="contained" color="secondary" sx={{ marginRight: '8px', marginBottom: '8px' }}>
              <strong>Main Action</strong>
            </Button>
            <Button variant="outlined" color="secondary" sx={{ marginRight: '8px', marginBottom: '8px' }}>
              <strong>Other Action</strong>
            </Button>
            <Button variant="outlined" color="secondary" sx={{ marginRight: '8px', marginBottom: '8px' }}>
              <strong>Other Action</strong>
            </Button>
            <Button variant="outlined" color="secondary" sx={{ marginRight: '8px', marginBottom: '8px' }}>
              <strong>Other Action</strong>
            </Button>
            <Button variant="outlined" color="secondary" sx={{ marginRight: '8px', marginBottom: '8px' }}>
              <strong>...</strong>
            </Button>
          </Box>

          <Typography sx={{ marginBottom: '1rem', borderBottom: '1px solid' }}>Current Season</Typography>
          <Grid rows={sampleRows} columns={sampleColumns} />
          <Typography sx={{ marginBottom: '1rem', marginTop: '2rem', borderBottom: '1px solid' }}>Previous Season</Typography>
          <Grid rows={sampleRows} columns={sampleColumns} />
          <Typography sx={{ marginBottom: '1rem', marginTop: '2rem', borderBottom: '1px solid' }}>Aggregate</Typography>
          <Grid rows={sampleRows} columns={sampleColumns} />
        </Box>
      </PlayerProvider>
    </>
  )
}

export default Player
