name: Beta Frontend Workflow

on:
  pull_request:
    paths:
      - "frontends/beta-frontend/**"
  push:
    branches:
      - main
    paths:
      - "frontends/beta-frontend/**"

jobs:

  node-workflow:
    uses: ./.github/workflows/node.yml
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    secrets: inherit
    with:
      FE_NAME: "beta-frontend"
      PROJECT_PATH: "services/beta-frontend"
      AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
      AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
      AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}