name: beta-frontend.yml

on:
  pull_request:
    paths:
      - "frontends/beta-frontend/**"
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
    paths:
      - "frontends/beta-frontend/**"

jobs:
  merge-request-job:
    uses: ./.github/workflows/default_npm_service.yml
    if: github.event_name == 'pull_request'
    secrets: inherit
    with:
      FE_NAME: "beta-frontend"
      DOCKER_IMAGE_GENERATION: "false"

  push-main-job:
    uses: ./.github/workflows/default_npm_service.yml
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      FE_NAME: "beta-frontend"

  # tag-job:
  #   uses: ./.github/workflows/default_npm_service.yml
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  #   secrets: inherit
  #   with:
  #     FE_NAME: "beta-frontend"
  #     RELEASE: "true"
