name: Main Service Workflow

on:
  pull_request:
    paths:
      - "services/main-service/**"
  push:
    branches:
      - main
    paths:
      - "services/main-service/**"

jobs: 

  maven-workflow:
    uses: ./.github/workflows/maven.yml
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    secrets: inherit
    with:
      SERVICE_NAME: "main-service"
      PROJECT_PATH: "services/main-service"