name: Main Workflow

run-name: ${{ github.actor }} fired main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main-workflow:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need this to ignore the project if no changes. If not, will always detect changes in all the services

      ##########
      ## LIBS ##
      ##########

      - name: security-lib pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "libs/security-lib"
          SERVICE_NAME: "security-lib"
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}
          DOCKER_IMAGE_GENERATION: "false"
          MVN_DEPLOY: "true"

      - name: event-lib pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "libs/event-lib"
          SERVICE_NAME: "event-lib"
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}
          DOCKER_IMAGE_GENERATION: "false"
          MVN_DEPLOY: "true"

      ##############
      ## SERVICES ##
      ##############

      - name: auth-service pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "services/auth-service"
          SERVICE_NAME: "auth-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      - name: gateway-service pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "services/gateway-service"
          SERVICE_NAME: "gateway-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      - name: player-service pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "services/player-service"
          SERVICE_NAME: "player-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      - name: match-service pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: "services/match-service"
          SERVICE_NAME: "match-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      - name: kafka-service pipeline
        uses: ./.github/actions/action-cargo-build
        with:
          PATH: "services/kafka-service"
          SERVICE_NAME: "kafka-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      - name: notifications-service pipeline
        uses: ./.github/actions/action-cargo-build
        with:
          PATH: "services/notifications-service"
          SERVICE_NAME: "notifications-service"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

      #########
      ## FEs ##
      #########

      - name: beta-frontend pipeline
        uses: ./.github/actions/action-npm-build
        with:
          PATH: "frontends/beta-frontend"
          FE_NAME: "beta-frontend"
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}
