name: Main Service Workflow

on:
  pull_request:
    paths:
      - "services/main-service/**"
  push:
    # tags:
    #   - 'v*.*.*'
    branches:
      - main
    paths:
      - "services/main-service/**"

env:
  SERVICE_NAME: "main-service"
  PROJECT_PATH: "services/main-service"
  AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
  AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
  AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
  SLACK_CICD_WEBHOOK: ${{ secrets.SLACK_CICD_WEBHOOK }}

jobs: 

  maven-pull-request:
    uses: ./.github/workflows/maven.yml
    if: github.event_name == 'pull_request'
    secrets: inherit
    with:
      DOCKER_IMAGE_GENERATION: "false"


  maven-main:
    uses: ./.github/workflows/maven.yml
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      DOCKER_IMAGE_GENERATION: "true"
