on:
    workflow_call:
        inputs:
            PROJECT_PATH:
                required: true
                type: string
            SERVICE_NAME:
                required: true
                type: string

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ${{ inputs.PROJECT_PATH }}/package-lock.json

            - name: Build
              run: |
                  cd ${{ inputs.PROJECT_PATH }}
                  npm install next
                  npm run build
              shell: bash

            - name: Test
              run: |
                  cd ${{ inputs.PROJECT_PATH }}
                  npm run test
              shell: bash

    docker-build-and-push:
        name: Build and Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-24.04
        needs: build
        steps:
            - uses: actions/checkout@v3

            - name: Docker Build and Push
              uses: ./.github/actions/docker
              with:
                  SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
                  PROJECT_PATH: ${{ inputs.PROJECT_PATH }}
              env:
                  AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
                  AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
                  AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
